[2024-06-13T23:22:03.243+0530] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-13T23:22:03.281+0530] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: weather_dag.is_weather_api_ready manual__2024-06-13T17:52:00.253432+00:00 [queued]>
[2024-06-13T23:22:03.300+0530] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: weather_dag.is_weather_api_ready manual__2024-06-13T17:52:00.253432+00:00 [queued]>
[2024-06-13T23:22:03.301+0530] {taskinstance.py:2306} INFO - Starting attempt 1 of 3
[2024-06-13T23:22:03.334+0530] {taskinstance.py:2330} INFO - Executing <Task(HttpSensor): is_weather_api_ready> on 2024-06-13 17:52:00.253432+00:00
[2024-06-13T23:22:03.342+0530] {standard_task_runner.py:63} INFO - Started process 73557 to run task
[2024-06-13T23:22:03.350+0530] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'weather_dag', 'is_weather_api_ready', 'manual__2024-06-13T17:52:00.253432+00:00', '--job-id', '21', '--raw', '--subdir', 'DAGS_FOLDER/weather_dag.py', '--cfg-path', '/tmp/tmpdjbucxvx']
[2024-06-13T23:22:03.355+0530] {standard_task_runner.py:91} INFO - Job 21: Subtask is_weather_api_ready
[2024-06-13T23:22:03.474+0530] {task_command.py:426} INFO - Running <TaskInstance: weather_dag.is_weather_api_ready manual__2024-06-13T17:52:00.253432+00:00 [running]> on host AlexMercer99.
[2024-06-13T23:22:03.738+0530] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='alex99mercer26263@gmail.com' AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='weather_dag' AIRFLOW_CTX_TASK_ID='is_weather_api_ready' AIRFLOW_CTX_EXECUTION_DATE='2024-06-13T17:52:00.253432+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-06-13T17:52:00.253432+00:00'
[2024-06-13T23:22:03.746+0530] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-13T23:22:03.832+0530] {baseoperator.py:400} WARNING - HttpSensor.execute cannot be called outside TaskInstance!
[2024-06-13T23:22:03.833+0530] {http.py:137} INFO - Poking: /data/2.5/weather?id=1259229&appid=8edf636a18dd28a56a2469fd9c9e5196
[2024-06-13T23:22:03.868+0530] {base.py:84} INFO - Using connection ID 'weathermap_api' for task execution.
[2024-06-13T23:22:04.595+0530] {base.py:294} INFO - Success criteria met. Exiting.
[2024-06-13T23:22:04.596+0530] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-13T23:22:04.623+0530] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=weather_dag, task_id=is_weather_api_ready, run_id=manual__2024-06-13T17:52:00.253432+00:00, execution_date=20240613T175200, start_date=20240613T175203, end_date=20240613T175204
[2024-06-13T23:22:04.688+0530] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-06-13T23:22:04.709+0530] {local_task_job_runner.py:222} INFO - ::endgroup::
