[2024-06-14T03:50:01.551+0530] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-14T03:50:01.571+0530] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: weather_dag.is_weather_api_ready scheduled__2024-06-13T22:15:00+00:00 [queued]>
[2024-06-14T03:50:01.581+0530] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: weather_dag.is_weather_api_ready scheduled__2024-06-13T22:15:00+00:00 [queued]>
[2024-06-14T03:50:01.582+0530] {taskinstance.py:2306} INFO - Starting attempt 1 of 3
[2024-06-14T03:50:01.607+0530] {taskinstance.py:2330} INFO - Executing <Task(HttpSensor): is_weather_api_ready> on 2024-06-13 22:15:00+00:00
[2024-06-14T03:50:01.611+0530] {standard_task_runner.py:63} INFO - Started process 115138 to run task
[2024-06-14T03:50:01.616+0530] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'weather_dag', 'is_weather_api_ready', 'scheduled__2024-06-13T22:15:00+00:00', '--job-id', '186', '--raw', '--subdir', 'DAGS_FOLDER/weather_dag.py', '--cfg-path', '/tmp/tmpwkg3evcm']
[2024-06-14T03:50:01.618+0530] {standard_task_runner.py:91} INFO - Job 186: Subtask is_weather_api_ready
[2024-06-14T03:50:01.686+0530] {task_command.py:426} INFO - Running <TaskInstance: weather_dag.is_weather_api_ready scheduled__2024-06-13T22:15:00+00:00 [running]> on host AlexMercer99.
[2024-06-14T03:50:01.815+0530] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='alex99mercer26263@gmail.com' AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='weather_dag' AIRFLOW_CTX_TASK_ID='is_weather_api_ready' AIRFLOW_CTX_EXECUTION_DATE='2024-06-13T22:15:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-06-13T22:15:00+00:00'
[2024-06-14T03:50:01.816+0530] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-14T03:50:01.827+0530] {baseoperator.py:400} WARNING - HttpSensor.execute cannot be called outside TaskInstance!
[2024-06-14T03:50:01.828+0530] {http.py:137} INFO - Poking: /data/2.5/weather?id=1259229&appid=8edf636a18dd28a56a2469fd9c9e5196
[2024-06-14T03:50:01.842+0530] {base.py:84} INFO - Using connection ID 'weathermap_api' for task execution.
[2024-06-14T03:50:02.384+0530] {base.py:294} INFO - Success criteria met. Exiting.
[2024-06-14T03:50:02.385+0530] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-14T03:50:02.397+0530] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=weather_dag, task_id=is_weather_api_ready, run_id=scheduled__2024-06-13T22:15:00+00:00, execution_date=20240613T221500, start_date=20240613T222001, end_date=20240613T222002
[2024-06-14T03:50:02.432+0530] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-06-14T03:50:02.448+0530] {local_task_job_runner.py:222} INFO - ::endgroup::
